services:
  - type: web
    name: musiclabel-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn music-label.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music_label.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        value: morsellimauriziotechweb
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: render.com