services:
  - type: web
    name: musiclabel-backend
    env: python
    region: oregon
    plan: free

    buildCommand: poetry install
    startCommand: gunicorn music_label.wsgi:application

    envVars:
      # Django core settings
      - key: DJANGO_SETTINGS_MODULE
        value: music_label.settings
      - key: SECRET_KEY
        value: morsellimauriziotechweb
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: render.com

      # Python & Poetry versions
      - key: PYTHON_VERSION
        value: 3.10
      - key: POETRY_VERSION
        value: 2.1.3

      # Optional: PostgreSQL database URL
      # - key: DATABASE_URL
      #   value: postgres://user:password@host:5432/dbname
