services:
  - type: web
    name: musiclabel-backend
    env: python
    buildCommand: poetry install
    startCommand: gunicorn music_label.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music_label.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: POETRY_VERSION
        value: 2.1.3
      - key: SECRET_KEY
        value: morsellimauriziotechweb
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: render.com
