services:
  # Web service
  - type: web
    name: record-label
    env: docker
    plan: starter
    buildCommand: apt-get update && apt-get install -y ffmpeg
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: record_label.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: record-label-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # SendGrid settings
      - key: SENDGRID_API_KEY
        sync: false
      - key: VERIFIED_SENDER_EMAIL
        value: projectmylabel@gmail.com

  # Database service
  - type: pserv
    name: record-label-db
    env: docker
    plan: starter
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    image: postgres:15-alpine
    envVars:
      - key: POSTGRES_USER
        fromService:
          type: web
          name: record-label
          envVarKey: POSTGRES_USER
      - key: POSTGRES_PASSWORD
        fromService:
          type: web
          name: record-label
          envVarKey: POSTGRES_PASSWORD
      - key: POSTGRES_DB
        fromService:
          type: web
          name: record-label
          envVarKey: POSTGRES_DB
